from plotting.plot import draw
from productions.p7 import P7
from productions.p1 import P1
from structure.graph import Graph
from structure.hyperedge import HyperEdge
from structure.node import Node


class G3:
    @staticmethod
    def run():
        g = Graph()
        n1 = Node(0, 0, "N1", False)
        n2 = Node(12, 0, "N2", False)
        n3 = Node(12, 12, "N3", False)
        n4 = Node(0, 12, "N4", False)
        n6 = Node(4, 3, "N6", False)
        n7 = Node(8, 3, "N7", False)
        n8 = Node(10, 6, "N8", False)
        n9 = Node(8, 9, "N9", False)
        n10 = Node(4, 9, "N10", False)
        n12 = Node(12, 6, "N12", False)
        e1 = HyperEdge((n1, n2), 'E', True, False)
        e2 = HyperEdge((n1, n4), 'E', False, False)
        e3 = HyperEdge((n2, n12), 'E', False, False)
        e4 = HyperEdge((n4, n3), 'E', False, False)
        e5 = HyperEdge((n10, n6), 'E', False, False)
        e6 = HyperEdge((n6, n7), 'E', False, False)
        e7 = HyperEdge((n7, n8), 'E', False, False)
        e8 = HyperEdge((n8, n9), 'E', False, False)
        e9 = HyperEdge((n9, n10), 'E', False, False)
        e10 = HyperEdge((n12, n8), 'E', False, False)
        e12 = HyperEdge((n12, n3), 'E', False, False)
        e15 = HyperEdge((n4, n10), 'E', False, False)
        e16 = HyperEdge((n3, n9), 'E', False, False)
        e17 = HyperEdge((n2, n7), 'E', False, False)
        e18 = HyperEdge((n1, n6), 'E', False, False)
        e19 = HyperEdge((n1, n6, n10, n4), 'E', False, False)
        e20 = HyperEdge((n2, n7, n8, n12), 'E', False, False)
        e21 = HyperEdge((n4, n3, n9, n10), 'E', False, False)
        e22 = HyperEdge((n6, n7, n8, n9, n10), 'E', False, False)
        e24 = HyperEdge((n12, n8, n9, n3), 'E', False, False)
        e25 = HyperEdge((n1, n2, n7, n6), 'E', False, False)
        g.add_node(n1)
        g.add_node(n2)
        g.add_node(n3)
        g.add_node(n4)
        g.add_node(n6)
        g.add_node(n7)
        g.add_node(n8)
        g.add_node(n9)
        g.add_node(n10)
        g.add_node(n12)
        g.add_edge(e1)
        g.add_edge(e2)
        g.add_edge(e3)
        g.add_edge(e4)
        g.add_edge(e5)
        g.add_edge(e6)
        g.add_edge(e7)
        g.add_edge(e8)
        g.add_edge(e9)
        g.add_edge(e10)
        g.add_edge(e12)
        g.add_edge(e15)
        g.add_edge(e16)
        g.add_edge(e17)
        g.add_edge(e18)
        g.add_hyper_edge(e19)
        g.add_hyper_edge(e20)
        g.add_hyper_edge(e21)
        g.add_hyper_edge(e22)
        g.add_hyper_edge(e24)
        g.add_hyper_edge(e25)


        draw(g)
        P7().apply(g)
        draw(g)
        P1().apply(g)
        draw(g)